### PR TITLE
Bump js sdk to 7.81.0

### PR DESCRIPTION
**Pull request by c298lee**

### CODE REVIEW

**Review by bruno-garcia — APPROVED** [review]
Nice! thanks @c298lee

**Comment by bruno-garcia** [comment]
Just realized in the previous bump it changed `package-lock.json` and `pnpm-lock.yaml`: https://github.com/getsentry/vanguard/pull/127/files

I wonder if that was a mistake or we need to bump both here.
Not familiar with pnpm

**Comment by c298lee** [comment]
I'm not sure either, the file was deleted in the [last commit](https://github.com/getsentry/vanguard/commit/c7e9fbd6b6564ac30192614b8c3100a3af278143), I can add it back if needed

**Comment by bruno-garcia** [comment]
@c298lee oh good that confirms then! It should be only one

**Pull request merged**
